/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorDinosaurios;
import entidades.Dinosaurios;
import javax.swing.JOptionPane;

/**
 *
 * @author ailin
 */
public class ModificarDino extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDino
     */
    public ModificarDino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDaModificar1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IDaModificar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreModf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dietaModf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        prefAlimentoModf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        domesticableModf = new javax.swing.JCheckBox();
        guardarDinoModf = new javax.swing.JButton();

        IDaModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDaModificar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Modificar nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar Dino");

        jLabel2.setText("Introduce el ID del dinosaurio a modificar:");

        IDaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDaModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Modificar nombre:");

        nombreModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreModfActionPerformed(evt);
            }
        });

        jLabel6.setText("Modificar dieta:");

        dietaModf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Herbivoro", "Carnivoro", "Otro" }));
        dietaModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietaModfActionPerformed(evt);
            }
        });

        jLabel7.setText("Preferencia alimento:");

        prefAlimentoModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefAlimentoModfActionPerformed(evt);
            }
        });

        jLabel8.setText("Si hes domesticable, marque la casilla:");

        domesticableModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domesticableModfActionPerformed(evt);
            }
        });

        guardarDinoModf.setText("Guardar");
        guardarDinoModf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDinoModfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(guardarDinoModf))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(8, 8, 8)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreModf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dietaModf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prefAlimentoModf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domesticableModf))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreModf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dietaModf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefAlimentoModf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(domesticableModf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardarDinoModf)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDaModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDaModificarActionPerformed

    private void IDaModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDaModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDaModificar1ActionPerformed

    private void nombreModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreModfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreModfActionPerformed

    private void dietaModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietaModfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietaModfActionPerformed

    private void prefAlimentoModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefAlimentoModfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefAlimentoModfActionPerformed

    private void domesticableModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domesticableModfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domesticableModfActionPerformed

    private void guardarDinoModfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDinoModfActionPerformed

        try {
        int id = Integer.parseInt(IDaModificar.getText().trim());
        String nombre = nombreModf.getText().trim();
        String dieta = (String) dietaModf.getSelectedItem();
        String preferencia = prefAlimentoModf.getText().trim();
        boolean domesticable = domesticableModf.isSelected();

        if (nombre.isEmpty() || dieta.isEmpty() || preferencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ControladorDinosaurios controlador = new ControladorDinosaurios();
        Dinosaurios dino = controlador.obtenerDinoPorId(id);

        if (dino == null) {
            JOptionPane.showMessageDialog(this, "No se encontro un dinosaurio con ese ID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dino.setNombre(nombre);
        dino.setTipo_DietaGeneral(dieta);
        dino.setPreferencia_Alimento(preferencia);
        dino.setDomesticable(domesticable);

        boolean actualizado = controlador.actualizarDino(dino);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Dinosaurio actualizado con exito.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // cerrar la ventana
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el dinosaurio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un numero valido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_guardarDinoModfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDaModificar;
    private javax.swing.JTextField IDaModificar1;
    private javax.swing.JComboBox<String> dietaModf;
    private javax.swing.JCheckBox domesticableModf;
    private javax.swing.JButton guardarDinoModf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreModf;
    private javax.swing.JTextField prefAlimentoModf;
    // End of variables declaration//GEN-END:variables
}
