/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import vistas.Tameos.AñadirTameo;
import vistas.Dinosaurios.VerDino;
import vistas.Dinosaurios.ModificarDino;
import vistas.Dinosaurios.EliminarDino;
import vistas.Dinosaurios.AñadirDino;
import vistas.Habitats.AñadirHabitat;
import vistas.Habitats.BuscarHabitat;
import vistas.Habitats.EliminarHabitat;
import vistas.Habitats.ModificarHabitat;
import vistas.Tameos.BuscarTameo;
import vistas.Tameos.EliminarTameo;
import vistas.Tameos.ModificarTameo;

/**
 *
 * @author ailin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        añadirDino = new javax.swing.JButton();
        modifDino = new javax.swing.JButton();
        verDino = new javax.swing.JButton();
        eliminarDino = new javax.swing.JButton();
        añadirTameo = new javax.swing.JButton();
        modificarTameo = new javax.swing.JButton();
        eliminarTameo = new javax.swing.JButton();
        verTameo = new javax.swing.JButton();
        añadirHabitatDino = new javax.swing.JButton();
        modificarHabitatDino = new javax.swing.JButton();
        verHabitatDino = new javax.swing.JButton();
        EliminarHabitatDino = new javax.swing.JButton();

        button1.setLabel("button1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO A ARKMINO");
        jLabel1.setToolTipText("");

        añadirDino.setBackground(new java.awt.Color(255, 255, 255));
        añadirDino.setForeground(new java.awt.Color(0, 0, 0));
        añadirDino.setText("Añadir dinosaurio");
        añadirDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirDinoActionPerformed(evt);
            }
        });

        modifDino.setBackground(new java.awt.Color(255, 255, 255));
        modifDino.setForeground(new java.awt.Color(0, 0, 0));
        modifDino.setText("Modificar dinosaurio");
        modifDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifDinoActionPerformed(evt);
            }
        });

        verDino.setBackground(new java.awt.Color(255, 255, 255));
        verDino.setForeground(new java.awt.Color(0, 0, 0));
        verDino.setText("Ver dinosaurio");
        verDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDinoActionPerformed(evt);
            }
        });

        eliminarDino.setBackground(new java.awt.Color(255, 255, 255));
        eliminarDino.setForeground(new java.awt.Color(0, 0, 0));
        eliminarDino.setText("Eliminar dinosaurio");
        eliminarDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDinoActionPerformed(evt);
            }
        });

        añadirTameo.setBackground(new java.awt.Color(255, 255, 255));
        añadirTameo.setForeground(new java.awt.Color(0, 0, 0));
        añadirTameo.setText("Añadir tameo");
        añadirTameo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirTameoActionPerformed(evt);
            }
        });

        modificarTameo.setBackground(new java.awt.Color(255, 255, 255));
        modificarTameo.setForeground(new java.awt.Color(0, 0, 0));
        modificarTameo.setText("Modificar tameo");
        modificarTameo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTameoActionPerformed(evt);
            }
        });

        eliminarTameo.setBackground(new java.awt.Color(255, 255, 255));
        eliminarTameo.setForeground(new java.awt.Color(0, 0, 0));
        eliminarTameo.setText("Eliminar tameo");
        eliminarTameo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTameoActionPerformed(evt);
            }
        });

        verTameo.setBackground(new java.awt.Color(255, 255, 255));
        verTameo.setForeground(new java.awt.Color(0, 0, 0));
        verTameo.setText("Ver tameo");
        verTameo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTameoActionPerformed(evt);
            }
        });

        añadirHabitatDino.setBackground(new java.awt.Color(255, 255, 255));
        añadirHabitatDino.setForeground(new java.awt.Color(0, 0, 0));
        añadirHabitatDino.setText("Añadir habitat");
        añadirHabitatDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirHabitatDinoActionPerformed(evt);
            }
        });

        modificarHabitatDino.setBackground(new java.awt.Color(255, 255, 255));
        modificarHabitatDino.setForeground(new java.awt.Color(0, 0, 0));
        modificarHabitatDino.setText("Modificar habitat");
        modificarHabitatDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarHabitatDinoActionPerformed(evt);
            }
        });

        verHabitatDino.setBackground(new java.awt.Color(255, 255, 255));
        verHabitatDino.setForeground(new java.awt.Color(0, 0, 0));
        verHabitatDino.setText("Ver habitat");
        verHabitatDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHabitatDinoActionPerformed(evt);
            }
        });

        EliminarHabitatDino.setBackground(new java.awt.Color(255, 255, 255));
        EliminarHabitatDino.setForeground(new java.awt.Color(0, 0, 0));
        EliminarHabitatDino.setText("Eliminar habitat");
        EliminarHabitatDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarHabitatDinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarDino, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(añadirDino)
                            .addComponent(modifDino)
                            .addComponent(verDino))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(verTameo)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eliminarTameo)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modificarTameo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(añadirTameo)
                                            .addGap(8, 8, 8))))))))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añadirHabitatDino, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modificarHabitatDino, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verHabitatDino, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EliminarHabitatDino, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirDino)
                    .addComponent(añadirTameo)
                    .addComponent(añadirHabitatDino))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifDino)
                    .addComponent(modificarTameo)
                    .addComponent(modificarHabitatDino))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verDino)
                    .addComponent(verTameo)
                    .addComponent(verHabitatDino))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarDino)
                    .addComponent(eliminarTameo)
                    .addComponent(EliminarHabitatDino))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifDinoActionPerformed
        // TODO add your handling code here:
        ModificarDino frame = new ModificarDino();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();                             // Cierra el frame actual (principal)
    }//GEN-LAST:event_modifDinoActionPerformed

    private void verDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDinoActionPerformed
        // TODO add your handling code here:
        VerDino frame = new VerDino();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();                             // Cierra el frame actual (principal)
    }//GEN-LAST:event_verDinoActionPerformed

    private void eliminarDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDinoActionPerformed
        // TODO add your handling code here:
        EliminarDino frame = new EliminarDino();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();                             // Cierra el frame actual (principal)
    }//GEN-LAST:event_eliminarDinoActionPerformed

    private void añadirDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirDinoActionPerformed
        // TODO add your handling code here:
        AñadirDino frame = new AñadirDino();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();                             // Cierra el frame actual (principal)
    }//GEN-LAST:event_añadirDinoActionPerformed

    private void añadirTameoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirTameoActionPerformed
        // TODO add your handling code here:
        AñadirTameo frame = new AñadirTameo();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();  
    }//GEN-LAST:event_añadirTameoActionPerformed

    private void modificarTameoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTameoActionPerformed
        // TODO add your handling code here:
        ModificarTameo frame = new ModificarTameo();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();  
    }//GEN-LAST:event_modificarTameoActionPerformed

    private void eliminarTameoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTameoActionPerformed
        // TODO add your handling code here:
        EliminarTameo frame = new EliminarTameo();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_eliminarTameoActionPerformed

    private void verTameoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTameoActionPerformed
        // TODO add your handling code here:
        BuscarTameo frame = new BuscarTameo();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();      
    }//GEN-LAST:event_verTameoActionPerformed

    private void añadirHabitatDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirHabitatDinoActionPerformed
        // TODO add your handling code here:
        AñadirHabitat frame = new AñadirHabitat();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_añadirHabitatDinoActionPerformed

    private void modificarHabitatDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarHabitatDinoActionPerformed
        // TODO add your handling code here:
        ModificarHabitat frame = new ModificarHabitat();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_modificarHabitatDinoActionPerformed

    private void verHabitatDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHabitatDinoActionPerformed
        // TODO add your handling code here:
        BuscarHabitat frame = new BuscarHabitat();
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_verHabitatDinoActionPerformed

    private void EliminarHabitatDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarHabitatDinoActionPerformed
        // TODO add your handling code here:
        EliminarHabitat frame = new EliminarHabitat();     
        frame.setLocationRelativeTo(null);     // Centrar en pantalla
        frame.setResizable(false);             // No redimensionable
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarHabitatDinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarHabitatDino;
    private javax.swing.JButton añadirDino;
    private javax.swing.JButton añadirHabitatDino;
    private javax.swing.JButton añadirTameo;
    private java.awt.Button button1;
    private javax.swing.JButton eliminarDino;
    private javax.swing.JButton eliminarTameo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifDino;
    private javax.swing.JButton modificarHabitatDino;
    private javax.swing.JButton modificarTameo;
    private javax.swing.JButton verDino;
    private javax.swing.JButton verHabitatDino;
    private javax.swing.JButton verTameo;
    // End of variables declaration//GEN-END:variables
}
